use a card token and call API to create payment
Mastercard-Gateway/woocommerce-simplify-payment-gateway-plugin pull request #32
Opened 2021-01-18 17:44 UTC by BlainMaguire

Use card token with create payment via the API on the woocommerce side.

2021-01-18 20:15 UTC, kennanseno commented on includes/class-payment-gateway.php
>  		// Transaction mode = Payment/Purchase
worth cleaning up the comment?

2021-01-18 20:17 UTC, kennanseno commented on includes/class-payment-gateway.php
> +		return 'create.token';
Do we need changes in the docs(readme?)?

2021-01-18 23:14 UTC, oconnort requested changes

2021-01-18 23:14 UTC, oconnort commented on includes/class-payment-gateway.php
> +					WC()->cart->empty_cart();
We need to add the `order_complete` check in here too like we did before and update the order status to complete as unlike the Authorisation below, there are no more actions for the merchant.

2021-01-20 10:05 UTC, BlainMaguire commented on includes/class-payment-gateway.php
> +			$pass_tokens['token'] = $cart_token;
For the return create.token, you mean we don't need the function? I can remove that,

My first stab at this was to build up a createPayment myself and handle the errors. So I had my own array.

But then I saw the do_payment function and thought it would be better to reuse it. The function expects an array, as it merges it for the payments call. I don't think the naming inside do_payment is correct. 'cart_token' (should be card) and we don't just pass a token, it can be anything we want to include in an associative array for creating the payment.

2021-01-20 10:29 UTC, BlainMaguire commented on includes/class-payment-gateway.php
> +					WC()->cart->empty_cart();
the logic that I've seen throughout (and I'm reusing) is if payment status == approved, then set order status completed. it simply doesn't set anything in on the order the cases things weren't approved on the payment (or refund) api calls.

2021-01-22 11:07 UTC, BlainMaguire commented on includes/class-payment-gateway.php
>  		// Transaction mode = Payment/Purchase
cleaned up.

2021-01-22 13:03 UTC, BlainMaguire commented on includes/class-payment-gateway.php
> +		return 'create.token';
I don't think so either, as per Tom's explanation.

2021-01-22 13:05 UTC, oconnort requested changes

2021-01-22 13:05 UTC, oconnort commented on includes/class-payment-gateway.php
> +				'amount'      => $this->get_total($order), // In cents. Rounding to avoid floating point errors.
We should add the same protection from the Authorize function, so nobody can change the amount:
``` php
if ( (int) $amount !== $this->get_total( $order ) ) {
	wc_add_notice( 'Payment amount mismatch', 'error' );
	wp_redirect( wc_get_page_permalink( 'cart' ) );
}
```

2021-01-22 13:05 UTC, BlainMaguire commented on includes/class-payment-gateway.php
> +			$pass_tokens['token'] = $cart_token;
I see what you mean now, looks like I just patched in my changes in and didn't remove the old code. I've tidied it up now.

2021-01-22 13:22 UTC, BlainMaguire commented on includes/class-payment-gateway.php
> +				'amount'      => $this->get_total($order), // In cents. Rounding to avoid floating point errors.
It should. I'm not sure why the parameter for amount is being ignored (also setting a default of 0, making it optional, I don't think a payment will go through in that case). I will change it.

I will add the order/amount check. Should be coming from $_REQUEST['amount'], right? (because otherwise I'm checking $order == $order).

2021-01-22 13:43 UTC, oconnort commented on includes/class-payment-gateway.php
> +				'amount'      => $this->get_total($order), // In cents. Rounding to avoid floating point errors.
We should only every process the order total and ignore the amount request parameter when paying. 
We don't a situation where somebody manipulates that value and tries to pay a different amount.

2021-01-27 09:00 UTC, oconnort commented on includes/class-payment-gateway.php
> +		$plugin_path = dirname( __FILE__ , 2 ) . '/woocommerce-simplify-payment-gateway.php' ;
Does this need to be wrapped in a try/catch in case the it blows up?
Do all versions of WooCommerce/PHP support this lookup and if not, we need to update the README to say so.

2021-01-27 13:27 UTC, BlainMaguire commented on includes/class-payment-gateway.php
> +		$plugin_path = dirname( __FILE__ , 2 ) . '/woocommerce-simplify-payment-gateway.php' ;
These methods should handle bad paths and the like with just coming back with an empty associative array. Tested that on php7. I can add a try/catch to be absolutely sure we set it. (issues with pushing to the repo at the moment).

2021-01-27 14:56 UTC, oconnort approved these changes
I think this looks good now. 
We need to regression test the changes and ensure the tokenization flow works as expected for both Payment & Auth/capture flows.

2021-01-28 21:02 UTC, merged